export { default as useStorage, type T_SyntheticStorage } from './useStorage.js'
export { default as useLocalStorage } from './useLocalStorage.js'
export { default as useSessionStorage } from './useSessionStorage.js'
export { default as useIndexedStorage } from './useIndexedStorage.js'
export { default as createIndexedStorage } from './createIndexedStorage.js'
