export { default as useStorage, type T_SyntheticStorage } from './useStorage'
export { default as useLocalStorage } from './useLocalStorage'
export { default as useSessionStorage } from './useSessionStorage'
export { default as useIndexedStorage } from './useIndexedStorage'
export { default as createIndexedStorage } from './createIndexedStorage'
